### ISSUE TITLE
Decimal number displayed differently

### ISSUE THREAD

**Issue by Duologic** [CertainLach/jrsonnet#108]
Just a difference I found but this time I actually like this change but it does make it harder to switch back/forth between versions.  Perhaps this is something that needs fixing in the go version? :shrug: 

```
➜ jsonnet -e 0.97
0.96999999999999997

➜ jrsonnet -e 0.97
0.97
```

**Comment by CertainLach** [comment]
❯ nix run nixpkgs#go-jsonnet -- -e "std.manifestJson(0.97)"
"0.97"
❯ nix run nixpkgs#go-jsonnet -- -e "std.toString(0.97)"
"0.96999999999999997"
❯ nix run nixpkgs#go-jsonnet -- -e 0.97
0.96999999999999997

❯ nix run nixpkgs#jsonnet -- -e "std.manifestJson(0.97)"
"0.96999999999999997"
❯ nix run nixpkgs#jsonnet -- -e "std.toString(0.97)"
"0.96999999999999997"
❯ nix run nixpkgs#jsonnet -- -e 0.97
0.96999999999999997

❯ cargo run -- -e "std.manifestJson(0.97)"
"0.97"
❯ cargo run -- -e "std.toString(0.97)"
"0.97"
❯ cargo run -- -e 0.97
0.97

Well... It looks like an inconsistency, but I wonder how/should it be fixed in jrsonnet?
In jrsonnet, -e output is serialized in the same way as `std.manifestJson` does.

**Comment by Duologic** [comment]
This turns out to be more interesting than I expected, @sparkprime wdyt?

**Comment by Duologic** [comment]
FYI, I've brought this up on the #jsonnet Slack channel on Kubernetes public Slack, finding more inconsistencies.

**Comment by Duologic** [comment]
I've made an upstream issue (https://github.com/google/go-jsonnet/issues/718), I think it should be fixed there, closing this issue.
