### ISSUE TITLE
How to eval arbitrary expressions against a `Val` (v0.5)

### ISSUE THREAD

**Issue by cloneable** [CertainLach/jrsonnet#116]
Hi! First, let me thank you for this set of excellent crates! I'm having a lot of fun prototyping a new jsonnet tool.

I'd like to offer the ability to specify an expression in addition to a jsonnet file. This expression is evaluated in the context of the file's `Val`, so one can inspect the value of specific fields or the result of a function without changing the file, somewhat similar to `jq`, but with a jsonnet expression.

Example:

```jsonnet
// my.jsonnet
{
  a: {
    b: [{
      c: 123
    }]
  }
}
```

`cli -f my.jsonnet -e 'a.b[0].c'` outputs `123`.

I looked around and tried a few things, but can't figure out how to combine the `Val` of the imported file with the parsed expression. Is there an easy way? Or do I have to programmatically create an `ObjValue` with fields for both and then evaluate the expression field?

```jsonnet
{
  a: {
    b: [{
      c: 123
    }]
  }

  exp:: $.a.b[0].c
}.exp
```

This would be a bit tedious to get right and limits the expressions I can use.

Thanks for any hints!

**Comment by CertainLach** [comment]
I think it would be easier to assign expression value to another context variable, i.e. `_`, and then evaluate another argument in the resulting context:

`-f my.jsonnet -e '_.a.b[0].c' -e '_ + 2'`

Unfortunately, without resolving to using `Context` and `mod evaluate` directly, it is only possible to do using globals:
https://github.com/CertainLach/jrsonnet/blob/aeb8b35c0ae24396c8ea28fe64d0cfc9b8b265a3/crates/jrsonnet-stdlib/src/lib.rs#L382

It would be better to implement `fn evaluate_snippet_in_context` helper on State; I'll think about it.

**Comment by cloneable** [comment]
Great! Thank you! Only if it's not too much work, though this could be a nice addition to the jrsonnet cli, too. I'll have a closer look at the `evaluate` module.

**Comment by bruno-delfino1995** [comment]
I've built this sort of thing [on kct](https://github.com/bruno-delfino1995/kct/blob/b1d52079608c77960e33d2da6d662dbc7894fa73/crates/kct_kube/src/ingestor/mod.rs#L85), but I used an accumulator to keep track of my paths and didn't bother about arrays. I would benefit from this if it could be done at the evaluator level and reduce the amount of output, but I guess that's not the place to put it because it'll probably open many edge cases.

@CertainLach, couldn't you use the $ reference since it refers to the outermost object?

**Comment by CertainLach** [comment]
Well, you can redefine $ for the context, but it would not be quite intuitive in some cases.

**Comment by CertainLach** [comment]
I have implemented helper for such feature, and have added it to jrsonnet standard cli under the `exp-apply` feature flag.

```rust
	#[allow(unused_mut)]
	let mut val = apply_tla(s.clone(), &tla, val)?;

	#[cfg(feature = "exp-apply")]
	for apply in opts.input.exp_apply {
		use jrsonnet_evaluator::{InitialUnderscore, Thunk};
		val = s.evaluate_snippet_with(
			"<exp_apply>".to_owned(),
			&apply,
			InitialUnderscore(Thunk::evaluated(val)),
		)?;
	}
```

Usage for the standard cli:
```shell
$ jrsonnet -e 2 --exp-apply '_ + 2' --exp-apply '_ * 2'
8
```

The reason why `_` is used for such binding instead of `$`, is because by spec, `$` is a outer-most OBJECT, not an arbitrary value, and jrsonnet only supports it being an object.

**Comment by cloneable** [comment]
Neat!

```
$ jrsonnet -e '{ foo: ["bar"] }' --exp-apply '_ + { foo+: ["baz"] }'
{
   "foo": [
      "bar",
      "baz"
   ]
}
```

Thanks a lot! I'm gonna take a look at the implementation soon.

**Comment by cloneable** [comment]
So I've been playing around with this and it works perfectly! Thank you! Already integrated this into my demo tool. I understand this feature might still change or get kicked out again before 0.5 is released, but right now for my demo this is great.
Thanks again! Feel free to close the issue.
