### ISSUE TITLE
jrsonnet-stdlib takes very long time to build?

### ISSUE THREAD

**Issue by iwinux** [CertainLach/jrsonnet#129]
Regardless of the shitty MacBook Pro that I'm using, jrsonnet-stdlib ranks the slowest crate in `cargo build` timings. It spends 90+% of the build time on codegen, which seems related to the `codegenerated-stdlib` feature?

## Env

* CPU: Intel i5-1038NG7 (8) @ 2.00GHz
* Rust 1.71.1 (eb26296b5 2023-08-03)
* Host: x86_64-apple-darwin
* Target: x86_64-apple-darwin
* jrsonnet-stdlib v0.5.0-pre95

## Build

```bash
cargo clean
cargo build --release --timings
```

## With Feature `codegenerated-stdlib`

<img width="984" alt="image" src="https://github.com/CertainLach/jrsonnet/assets/98864/145dd6e7-2d22-45f8-954d-e64825e7a2aa">

<img width="1414" alt="image" src="https://github.com/CertainLach/jrsonnet/assets/98864/58fa5719-7531-4010-bb1c-7677bf661a50">

## Without Feature `codegenerated-stdlib`

```toml
[dependencies.jrsonnet-stdlib]
version = "0.5.0-pre95"
default-features = false
features = ["exp-preserve-order"]
```

<img width="801" alt="image" src="https://github.com/CertainLach/jrsonnet/assets/98864/7d2d2e3c-1cbf-4be5-baf2-c8535ef6ee53">

<img width="1447" alt="image" src="https://github.com/CertainLach/jrsonnet/assets/98864/33742b71-f803-4e92-a654-893bff9babde">

**Comment by CertainLach** [comment]
Previously, codegenerated-stdlib caused huge startup speedups.

Not much nowadays, as most of the standard library has been moved to native code (https://github.com/CertainLach/jrsonnet/blob/master/crates/jrsonnet-stdlib/src/std.jsonnet), but it's still better than parsing it every time.

I think this is normal, because it generates very large function, which llvm tries (and succeeds) to optimize a lot.

**Comment by iwinux** [comment]
Understood. Thank you!
