### ISSUE TITLE
I want to implement async function as native function in jsonnet how can I ? Please could you help

### ISSUE THREAD

**Issue by redoC-A2k** [CertainLach/jrsonnet#158]
Here's where I am implementing trait - https://github.com/redoC-A2k/EdgeChains/blob/abb2398ec030ee43817324fbbfc2993e6620e08c/JS/jsonnet/src/lib.rs#L227

We are using wasm bindgen and executing native js function in jsonnet . Normal function works fine but async functions do not .

**Comment by CertainLach** [comment]
Jsonnet is synchronous
It is possible to implement async imports, but not async functions

**Comment by CertainLach** [comment]
Jrsonnet is synchronous.
You can't call an async function from sync code unless you execute this function in another thread (or climb the stack up and poll jrsonnet code until it will be able to get already executed function output synchronously), and that is not possible with JS and WASM.

It might be possible in some cases to replace synchronous function call with asynchronous import (which jrsonnet supports), I.e it is not possible to implement `myStd.fetch("http://...")` in JS, but it is possible to do it using `import "http://..."`, because imports might be async: https://github.com/CertainLach/jrsonnet/blob/master/crates/jrsonnet-evaluator/src/async_import.rs#L294

**Comment by redoC-A2k** [comment]
Thanks a lot for your help , for now we have used sync-rpc library to make asynchronous function synchronous in nodejs .
