### ISSUE TITLE
Release non-x86-64 binaries

### ISSUE THREAD

**Issue by JarvisCraft** [CertainLach/jrsonnet#35]
# Description

Currently only x86-64 builds are released. Support for the remaining Tier-1 architectures should also be added as part of `Release` workflow.

**Comment by bruno-delfino1995** [comment]
I was trying this out using the default runners from GitHub. However, there's no option to change the runner's architecture from `amd64` to `i386`, making it troublesome to build for `x32` targets of Tier 1.

I managed to [build](https://github.com/bruno-delfino1995/jrsonnet/runs/2623395431) for all the platforms, but the workflow isn't pretty. We could leverage the rust ecosystem for these builds. What do you think about adding a section about installing the CLI using cargo instead of these pre-built binaries?

**Comment by CertainLach** [comment]
> What do you think about adding a section about installing the CLI using cargo instead of these pre-built binaries?

CLI can't be installed via cargo, because it depends on not yet released version of clap, and crates with git dependencies can't be published to crates.io

**Comment by bruno-delfino1995** [comment]
I totally forgot that. Thank you for bringing it up!

Should I open a PR with the new workflow?

**Comment by messense** [comment]
FYI, I've submitted jrsonnet to homebrew: https://github.com/Homebrew/homebrew-core/pull/80170 , on macOS users can install it by`brew install jrsonnet`.
